"""Production-quality CLAUDE.md generator.

Per tasks/claude-code-prompt.md Feature 3. Renders the indexed atoms as a
topic-grouped, citation-inlined Markdown file that's optimized for both human
review and AI-agent ingestion.

Layout:

    # CLAUDE.md — Auto-generated conventions for <repo>
    > metadata header

    ## <Topic name>
    ### Rules
    - **<rule summary>** <rationale> [Scope: …] (Source: PR #N, commit abc)
    ### Conventions
    - <atom summary>

    …

    ---
    *footer*
"""
from __future__ import annotations

import json
import re
import sqlite3
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path

_COMMIT_RE = re.compile(r"^commit:([0-9a-f]{7,40})", re.IGNORECASE)
_PR_RE = re.compile(r"^pr:(\d+)")
_NOTE_RE = re.compile(r"^note:(.+)")
_FILE_RE = re.compile(r"^file:(.+)")


def _format_citation(refs: list[str]) -> str:
    """Render a deduped, sorted citation string from source_refs.

    Examples:
        ['pr:3:description', 'pr:3:review:3'] → 'PR #3'
        ['commit:abc123…']                    → 'commit abc123'
        ['note:2026-05-19T01:20:34']          → 'note 2026-05-19'
        ['file:utils/db_helper.py']           → 'file utils/db_helper.py'
    """
    if not refs:
        return ""
    prs: list[str] = []
    commits: list[str] = []
    notes: list[str] = []
    files: list[str] = []
    seen: set[str] = set()
    for ref in refs:
        if m := _PR_RE.match(ref):
            tag = f"PR #{m.group(1)}"
            if tag not in seen:
                prs.append(tag)
                seen.add(tag)
        elif m := _COMMIT_RE.match(ref):
            tag = f"commit {m.group(1)[:7]}"
            if tag not in seen:
                commits.append(tag)
                seen.add(tag)
        elif m := _NOTE_RE.match(ref):
            date = m.group(1).split("T")[0]
            tag = f"note {date}"
            if tag not in seen:
                notes.append(tag)
                seen.add(tag)
        elif m := _FILE_RE.match(ref):
            tag = f"file {m.group(1)}"
            if tag not in seen:
                files.append(tag)
                seen.add(tag)
        else:
            if ref not in seen:
                files.append(ref)
                seen.add(ref)
    parts = prs + commits + notes + files
    return ", ".join(parts)


def _load(db_path: Path) -> tuple[list[dict], list[dict]]:
    conn = sqlite3.connect(db_path)
    try:
        atom_rows = conn.execute(
            "SELECT id, summary, rationale, scope, source_refs, confidence, "
            "is_rule, created_at FROM atoms"
        ).fetchall()
        topic_rows = conn.execute(
            "SELECT id, name, summary, atom_ids FROM topics"
        ).fetchall()
    finally:
        conn.close()

    atoms = []
    for r in atom_rows:
        try:
            refs = json.loads(r[4] or "[]")
        except (TypeError, ValueError):
            refs = []
        atoms.append({
            "id": r[0],
            "summary": r[1],
            "rationale": r[2],
            "scope": r[3],
            "source_refs": refs,
            "confidence": r[5] or 0.0,
            "is_rule": bool(r[6]),
            "created_at": r[7],
        })

    topics = []
    for r in topic_rows:
        try:
            atom_ids = json.loads(r[3] or "[]")
        except (TypeError, ValueError):
            atom_ids = []
        topics.append({
            "id": r[0],
            "name": r[1],
            "summary": r[2],
            "atom_ids": atom_ids,
        })
    return atoms, topics


def render(db_path: Path | str, repo_name: str) -> str:
    """Render the full CLAUDE.md text. Pure read; no side effects."""
    db_path = Path(db_path)
    atoms, topics = _load(db_path)
    by_id = {a["id"]: a for a in atoms}

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    n_atoms = len(atoms)
    n_rules = sum(1 for a in atoms if a["is_rule"])
    n_topics = len(topics)

    lines: list[str] = []
    lines.append(f"# CLAUDE.md — Auto-generated conventions for {repo_name}")
    lines.append("")
    lines.append(f"> Generated by ContextLayer.dev on {today}")
    lines.append(
        f"> Source: {n_atoms} atoms, {n_rules} rules, {n_topics} topics from git + PR history"
    )
    lines.append("> Regenerate: `contextlayer claude-md --repo .`")
    lines.append("")

    # Track which atoms have already been emitted under a topic so we can
    # render orphans (atoms with no topic) at the end.
    emitted: set[str] = set()

    # Preserve topic order from the DB (insertion / extraction order).
    for topic in topics:
        topic_atoms = [by_id[aid] for aid in topic["atom_ids"] if aid in by_id]
        if not topic_atoms:
            continue
        rules = sorted(
            [a for a in topic_atoms if a["is_rule"]],
            key=lambda a: -(a["confidence"] or 0.0),
        )
        conventions = sorted(
            [a for a in topic_atoms if not a["is_rule"]],
            key=lambda a: -(a["confidence"] or 0.0),
        )

        lines.append(f"## {topic['name']}")
        lines.append("")

        if rules:
            lines.append("### Rules")
            for a in rules:
                lines.append("- " + _format_atom_line(a, bold=True))
                emitted.add(a["id"])
            lines.append("")

        if conventions:
            lines.append("### Conventions")
            for a in conventions:
                lines.append("- " + _format_atom_line(a, bold=False))
                emitted.add(a["id"])
            lines.append("")

    orphans = [a for a in atoms if a["id"] not in emitted]
    if orphans:
        rules = sorted(
            [a for a in orphans if a["is_rule"]],
            key=lambda a: -(a["confidence"] or 0.0),
        )
        conventions = sorted(
            [a for a in orphans if not a["is_rule"]],
            key=lambda a: -(a["confidence"] or 0.0),
        )
        lines.append("## Other")
        lines.append("")
        if rules:
            lines.append("### Rules")
            for a in rules:
                lines.append("- " + _format_atom_line(a, bold=True))
            lines.append("")
        if conventions:
            lines.append("### Conventions")
            for a in conventions:
                lines.append("- " + _format_atom_line(a, bold=False))
            lines.append("")

    lines.append("---")
    lines.append(
        "*This file was auto-generated by [ContextLayer.dev](https://contextlayer-dev.vercel.app). "
        "To update, run `contextlayer claude-md --repo .`*"
    )
    lines.append("")
    return "\n".join(lines)


def _format_atom_line(atom: dict, *, bold: bool) -> str:
    """Render one atom as a single markdown bullet body (no leading '- ')."""
    summary = (atom["summary"] or "").strip()
    if not summary.endswith((".", "!", "?")):
        summary += "."
    head = f"**{summary}**" if bold else summary

    extras: list[str] = []
    if atom.get("rationale"):
        rationale = atom["rationale"].strip()
        if not rationale.endswith((".", "!", "?")):
            rationale += "."
        extras.append(rationale)
    if atom.get("scope"):
        extras.append(f"[Scope: {atom['scope']}]")
    citation = _format_citation(atom.get("source_refs") or [])
    if citation:
        extras.append(f"(Source: {citation})")

    return " ".join([head] + extras) if extras else head
